import { ref } from 'vue';

/**
 * Loads the manifest of available per-item Pip-Boy icons (generated by
 * scripts/convert-dds-icons.py at public/icons/pipboy/manifest.json) once, and
 * lets components ask whether a given item icon path has a converted icon.
 * Items whose path isn't present (e.g. modded items) fall back to a type icon.
 *
 * Icons: Consistent Pip-Boy Icons by ItsMeJesusHChrist (used with permission).
 */
const available = ref<Set<string>>(new Set());
let started = false;

function ensureLoaded(): void {
  if (started) return;
  started = true;
  fetch(`${import.meta.env.BASE_URL}icons/pipboy/manifest.json`)
    .then((r) => (r.ok ? r.json() : []))
    .then((paths: string[]) => {
      if (Array.isArray(paths)) available.value = new Set(paths);
    })
    .catch(() => {
      /* no manifest -> everything falls back to type icons */
    });
}

export function usePipboyIcons() {
  ensureLoaded();
  // Reads `available.value` so callers using it inside a computed stay reactive
  // once the manifest finishes loading.
  const hasIcon = (path?: string | null): boolean => !!path && available.value.has(path);
  return { hasIcon };
}
